const NothingHereCard = () => {
  return (
    <div className="w-full flex flex-col justify-center items-center">
      <img
        src="/assets/landing1.png"
        alt="Nothing Here Image, Generated by Stable Diffusion"
        className="w-[250px] h-[250px]"
      />
      {/* Subtitle */}
      <div className="text-center">
        <p className="text-xl mb-2 font-bold">No Notebooks to be found</p>
        <div className="text-gray-500 text-sm">
          Press &quot;+ Create&quot; to create some
        </div>
      </div>
    </div>
  );
};

export default NothingHereCard;
